### ISSUE TITLE
rundeckrun is not working with SSL/HTTPS

### ISSUE THREAD

**Issue by nicolas-g** [marklap/rundeckrun#21]
Hi,

I'm able to run jobs on Rundeck when the server is listening on the standard port 4440 on HTTP for security reasons I had to change the port to 4443 with HTTPS and my python program is not working anymore..

 
```
#!/usr/bin/python3

import sys
from rundeck.client import Rundeck

RUNDECK_SERVER='rundeck.mydomain.com'
RUNDECK_PORT=4443
PROTOCOL='https'
API_TOKEN="dfljLIUREJKDlkirleliufkJIFRE42"
JOB_ID="34334d4j9dj29-1989-40f7-8aa6-2b9a10399a2b"

rd = Rundeck(RUNDECK_SERVER, protocol=PROTOCOL, port=RUNDECK_PORT,api_token=API_TOKEN)

rd.run_job(JOB_ID, argString={'from':'Rundeckrun'})
```

Output : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 322, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 727, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 253, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 578, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 548, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zabbix_rundeck.py", line 50, in <module>
    rd.run_job(JOB_ID, argString={'Zabbix':'Auto-Healing'}, hostname=TARGET)
  File "/usr/lib/python3.4/site-packages/rundeck/client.py", line 247, in run_job
    execution = self._run_job(job_id, **kwargs)
  File "/usr/lib/python3.4/site-packages/rundeck/transforms.py", line 258, in wrapper
    results = func(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/rundeck/client.py", line 324, in _run_job
    return self.api.job_run(job_id, **kwargs)
  File "/usr/lib/python3.4/site-packages/rundeck/api.py", line 357, in job_run
    return self._exec(GET, 'job/{0}/run'.format(job_id), params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/rundeck/api.py", line 1053, in _exec
    method, url, params=params, data=data, parse_response=parse_response, **kwargs)
  File "/usr/lib/python3.4/site-packages/rundeck/api.py", line 224, in _exec
    method, url, params=params, data=data, parse_response=parse_response, **kwargs)
  File "/usr/lib/python3.4/site-packages/rundeck/connection.py", line 232, in call
    method, url, params=params, data=data, headers=headers, files=files, **kwargs)
  File "/usr/lib/python3.4/site-packages/rundeck/connection.py", line 284, in request
    method, url, params=params, data=data, headers=headers, files=files)
  File "/usr/lib/python3.4/site-packages/rundeck/connection.py", line 257, in request
    method, url, params=params, data=data, headers=headers, files=files)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

Versions installed
```
python3.4
pip3.4
rundeckrun=0.1.11
bottle=0.11.6
nose=1.3.0
requests=2.5.1
```

**Comment by marklap** [comment]
There's two ways around this.

1. \[*suggested*\] follow (the docs on the requests)[http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification] to enable successful verification of your SSL cert which I'm stunning is a self-signed cert. The keyword to pass to rundeckrun is `verify_cert` which gets translated to `verify` in the `requests` session object that rundeckrun instantiates.
2. Disable verification of SSL certs. Pass `verify=False` when creating the rundeckrun object (which again changes to `verify` in `requests`)..

**Comment by nicolas-g** [comment]
Thanks , that was the case a self-signed certificate.

**Comment by marklap** [comment]
Good to hear.
